"""initial_schema"""
from alembic import op
import sqlalchemy as sa

revision = '86d4708b7d33'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amc',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('official_website', sa.Text(), nullable=True),
    sa.Column('factsheet_page_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('fund_manager',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('industry',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('security',
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('nse_symbol', sa.Text(), nullable=True),
    sa.Column('bse_code', sa.Text(), nullable=True),
    sa.Column('security_type', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_canonical_name'), 'security', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_security_isin'), 'security', ['isin'], unique=True)
    op.create_index(op.f('ix_security_normalized_key'), 'security', ['normalized_key'], unique=False)
    op.create_table('factsheet_document',
    sa.Column('amc_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('factsheet_month', sa.Date(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('document_key', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current_version', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['amc_id'], ['amc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amc_id', 'factsheet_month', 'document_key', 'version_number'),
    sa.UniqueConstraint('amc_id', 'factsheet_month', 'document_type', 'sha256')
    )
    op.create_index('ix_document_amc_month', 'factsheet_document', ['amc_id', 'factsheet_month'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_month', sa.Date(), nullable=False),
    sa.Column('amc_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('documents_discovered', sa.Integer(), nullable=False),
    sa.Column('documents_downloaded', sa.Integer(), nullable=False),
    sa.Column('schemes_detected', sa.Integer(), nullable=False),
    sa.Column('equity_schemes_detected', sa.Integer(), nullable=False),
    sa.Column('schemes_successful', sa.Integer(), nullable=False),
    sa.Column('schemes_failed', sa.Integer(), nullable=False),
    sa.Column('holdings_inserted', sa.Integer(), nullable=False),
    sa.Column('new_securities', sa.Integer(), nullable=False),
    sa.Column('matched_securities', sa.Integer(), nullable=False),
    sa.Column('ambiguous_securities', sa.Integer(), nullable=False),
    sa.Column('gemini_fallbacks_used', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['amc_id'], ['amc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme',
    sa.Column('amc_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('scheme_name', sa.Text(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('scheme_code', sa.Text(), nullable=True),
    sa.Column('asset_class', sa.String(length=30), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('management_style', sa.String(length=20), nullable=True),
    sa.Column('benchmark', sa.Text(), nullable=True),
    sa.Column('additional_benchmark', sa.Text(), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('classification_status', sa.String(length=40), nullable=False),
    sa.Column('classification_evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amc_id'], ['amc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amc_id', 'canonical_name')
    )
    op.create_index(op.f('ix_scheme_amc_id'), 'scheme', ['amc_id'], unique=False)
    op.create_index(op.f('ix_scheme_asset_class'), 'scheme', ['asset_class'], unique=False)
    op.create_index(op.f('ix_scheme_category'), 'scheme', ['category'], unique=False)
    op.create_table('security_alias',
    sa.Column('security_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('alias_name', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('source_amc_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.ForeignKeyConstraint(['source_amc_id'], ['amc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'alias_name')
    )
    op.create_index(op.f('ix_security_alias_normalized_key'), 'security_alias', ['normalized_key'], unique=False)
    op.create_table('performance',
    sa.Column('scheme_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('identity_key', sa.Text(), nullable=False),
    sa.Column('plan_type', sa.Text(), nullable=True),
    sa.Column('option_type', sa.Text(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('scheme_return_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('benchmark_return_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('additional_benchmark_return_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('value_of_10000_scheme', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('value_of_10000_benchmark', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('value_of_10000_additional', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('source_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['factsheet_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'identity_key', 'as_of_date', 'period')
    )
    op.create_table('review_item',
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('scheme_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('review_type', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('candidate_value', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['factsheet_document.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_run.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_factsheet_section',
    sa.Column('factsheet_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('scheme_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('detected_scheme_name', sa.Text(), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('extraction_status', sa.String(length=40), nullable=False),
    sa.Column('raw_text_path', sa.Text(), nullable=True),
    sa.Column('raw_json_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['factsheet_document_id'], ['factsheet_document.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factsheet_document_id', 'start_page', 'detected_scheme_name')
    )
    op.create_table('scheme_manager_history',
    sa.Column('scheme_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fund_manager_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('experience_text', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['fund_manager_id'], ['fund_manager.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['factsheet_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_monthly_snapshot',
    sa.Column('scheme_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('aum_crore', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('average_aum_crore', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('equity_turnover_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('total_turnover_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('standard_deviation', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('beta', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('risk_free_rate_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('large_cap_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('mid_cap_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('small_cap_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('equity_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('reit_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('invit_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('debt_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('cash_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('other_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('debt_cash_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('scheme_riskometer', sa.Text(), nullable=True),
    sa.Column('benchmark_riskometer', sa.Text(), nullable=True),
    sa.Column('minimum_investment', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('minimum_additional', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('exit_load_text', sa.Text(), nullable=True),
    sa.Column('investment_objective', sa.Text(), nullable=True),
    sa.Column('scheme_description', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('complete_holdings', sa.Boolean(), nullable=False),
    sa.Column('field_provenance', sa.JSON(), nullable=True),
    sa.Column('extra_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('aum_crore IS NULL OR aum_crore >= 0'),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['factsheet_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'as_of_date')
    )
    op.create_index(op.f('ix_scheme_monthly_snapshot_as_of_date'), 'scheme_monthly_snapshot', ['as_of_date'], unique=False)
    op.create_table('scheme_plan',
    sa.Column('scheme_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('identity_key', sa.String(length=100), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=True),
    sa.Column('option_type', sa.String(length=20), nullable=True),
    sa.Column('idcw_suboption', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'identity_key')
    )
    op.create_table('sip_performance',
    sa.Column('scheme_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('identity_key', sa.Text(), nullable=False),
    sa.Column('plan_type', sa.Text(), nullable=True),
    sa.Column('option_type', sa.Text(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('scheme_xirr_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('benchmark_xirr_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('additional_benchmark_xirr_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('source_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['factsheet_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'identity_key', 'as_of_date', 'period')
    )
    op.create_table('holding',
    sa.Column('scheme_snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('security_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('industry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('weight_pct', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('market_value_crore', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('raw_company_name', sa.Text(), nullable=True),
    sa.Column('raw_industry_name', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.CheckConstraint('weight_pct >= 0 AND weight_pct <= 100'),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.ForeignKeyConstraint(['scheme_snapshot_id'], ['scheme_monthly_snapshot.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['factsheet_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_snapshot_id', 'security_id')
    )
    op.create_index(op.f('ix_holding_scheme_snapshot_id'), 'holding', ['scheme_snapshot_id'], unique=False)
    op.create_index(op.f('ix_holding_security_id'), 'holding', ['security_id'], unique=False)
    op.create_index('ix_holding_snapshot_weight', 'holding', ['scheme_snapshot_id', 'weight_pct'], unique=False)
    op.create_table('plan_monthly_metric',
    sa.Column('scheme_plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('expense_ratio_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('base_expense_ratio_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('source_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.CheckConstraint('expense_ratio_pct IS NULL OR expense_ratio_pct >= 0'),
    sa.CheckConstraint('nav IS NULL OR nav > 0'),
    sa.ForeignKeyConstraint(['scheme_plan_id'], ['scheme_plan.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['factsheet_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_plan_id', 'as_of_date')
    )
    op.create_table('sector_allocation',
    sa.Column('scheme_snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('industry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('calculated', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.ForeignKeyConstraint(['scheme_snapshot_id'], ['scheme_monthly_snapshot.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['factsheet_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_snapshot_id', 'industry_id')
    )
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_allocation')
    op.drop_table('plan_monthly_metric')
    op.drop_index('ix_holding_snapshot_weight', table_name='holding')
    op.drop_index(op.f('ix_holding_security_id'), table_name='holding')
    op.drop_index(op.f('ix_holding_scheme_snapshot_id'), table_name='holding')
    op.drop_table('holding')
    op.drop_table('sip_performance')
    op.drop_table('scheme_plan')
    op.drop_index(op.f('ix_scheme_monthly_snapshot_as_of_date'), table_name='scheme_monthly_snapshot')
    op.drop_table('scheme_monthly_snapshot')
    op.drop_table('scheme_manager_history')
    op.drop_table('scheme_factsheet_section')
    op.drop_table('review_item')
    op.drop_table('performance')
    op.drop_index(op.f('ix_security_alias_normalized_key'), table_name='security_alias')
    op.drop_table('security_alias')
    op.drop_index(op.f('ix_scheme_category'), table_name='scheme')
    op.drop_index(op.f('ix_scheme_asset_class'), table_name='scheme')
    op.drop_index(op.f('ix_scheme_amc_id'), table_name='scheme')
    op.drop_table('scheme')
    op.drop_table('ingestion_run')
    op.drop_index('ix_document_amc_month', table_name='factsheet_document')
    op.drop_table('factsheet_document')
    op.drop_index(op.f('ix_security_normalized_key'), table_name='security')
    op.drop_index(op.f('ix_security_isin'), table_name='security')
    op.drop_index(op.f('ix_security_canonical_name'), table_name='security')
    op.drop_table('security')
    op.drop_table('industry')
    op.drop_table('fund_manager')
    op.drop_table('amc')
    # ### end Alembic commands ###
